### PR TITLE
Filter dest addresses based on IngressIP

### LINKED ISSUE #25: Bug: Controller does not filter IP address family
The controller does not distinguish between IPv4 and IPv6 addresses. This breaks the appliance of nftables rules if the host nodes have an IPv4 and an IPv6 address (DualStack).

The controller tries to use IPv6 addresses in an IPv4 nftables rule. This leads to the failure of nftables when trying to apply the generated config:

```
Error: Could not resolve hostname: Address family for hostname not supported
```

### PR DESCRIPTION
**Pull request by ComradeOgilvy**
The host nodes of a cluster can have IPv4 and/or IPv6 addresses.
The controller does not distinguish the address families, which leads to
the fact that all addresses will be used as Destination Addresses
independent of the preferred IPFamily of the Service or the Ingress IP.

This commit adjusts getDestinationAddress to return two lists, one for
each supported address family.
To do so, functions to check the correctness of a textual representation
of an IP and to check the address family got implemented.
golang does not natively support the determination of the address family,
which is why the presence of ":" and "." is checked.

The GenerateModel function has been adjusted to use only IP addresses
of the same address family as the IngressIP as destination addresses.

Fixes #25

### CODE REVIEW

File: internal/controller/model_nodeport.go [hunk 1]
```diff
@@ -23,6 +27,14 @@ import (
...
 )
 
+var (
+	ErrUnknownAddressFamily = errors.New("cannot determine the correct IP address family")
+)
+
+var (
+	ErrInvalidIpAddress = errors.New("the string is not a valid textual representation of an IP address")
+)
+
```
Comment (horazont) [inline internal/controller/model_nodeport.go:37]: You can use a single var block for those.

File: internal/controller/model_nodeport.go [hunk 2]
```diff
@@ -40,27 +52,61 @@ func NewNodePortLoadBalancerModelGenerator(
...
+				addresses_v4 = append(addresses_v4, addr.Address)
+			}
+
+			nodeAddressIsIPv6, err := isIPv6Address(addr.Address)
+			if err != nil {
+				return nil, nil, err
+			}
+			if nodeAddressIsIPv6 {
+				addresses_v6 = append(addresses_v6, addr.Address)
+			}
```
Comment (horazont) [inline internal/controller/model_nodeport.go:97]: Do not exit the loop on a malformed IP address. Just skip that particular address.

File: internal/controller/model_nodeport.go [hunk 3]
```diff
@@ -40,27 +52,61 @@ func NewNodePortLoadBalancerModelGenerator(
...
+
+			if !nodeAddressIsIPv4 && !nodeAddressIsIPv6 {
+				return nil, nil, ErrUnknownAddressFamily
+			}
```
Comment (horazont) [inline internal/controller/model_nodeport.go:101]: Same here.

File: internal/controller/model_nodeport.go [hunk 4]
```diff
@@ -40,27 +52,61 @@ func NewNodePortLoadBalancerModelGenerator(
...
+func isValidIp(ipString string) (err error) {
+	ipParsed := net.ParseIP(ipString)
+	if ipParsed != nil {
+		return nil
+	}
+	return ErrInvalidIpAddress
+}
+
+func isIPv4Address(ipString string) (isIPv4 bool, err error) {
+	return strings.Count(ipString, ":") < 2, isValidIp(ipString)
```
Comment (horazont) [inline internal/controller/model_nodeport.go:64]: Why would a single : be ok?

File: internal/controller/model_nodeport.go [hunk 5]
```diff
@@ -40,27 +52,61 @@ func NewNodePortLoadBalancerModelGenerator(
...
+}
+
+func isIPv6Address(ipString string) (isIPv6 bool, err error) {
+	return strings.Count(ipString, ":") >= 2, isValidIp(ipString)
+}
```
Comment (horazont) [inline internal/controller/model_nodeport.go:69]: I think the `is*Address` functions do a bit too much. This is apparent from the error handling required below.

I think it would be cleaner to simply assume that a string is an IP address and require the caller to check for "being an IP address" first.

File: internal/controller/model_nodeport.go (hunk 4 above)
Comment (ComradeOgilvy) [reply internal/controller/model_nodeport.go:64]: If a Port is defined, but you are completely right. This must not be allowed here.

File: internal/controller/model_nodeport.go (hunk 2 above)
Comment (ComradeOgilvy) [reply internal/controller/model_nodeport.go:97]: Thanks, changed.

File: internal/controller/model_nodeport.go (hunk 3 above)
Comment (ComradeOgilvy) [reply internal/controller/model_nodeport.go:101]: Thanks, changed.

File: internal/controller/model_nodeport.go (hunk 1 above)
Comment (ComradeOgilvy) [reply internal/controller/model_nodeport.go:37]: Thanks, changed.

File: internal/controller/model_nodeport.go (hunk 5 above)
Comment (ComradeOgilvy) [reply internal/controller/model_nodeport.go:69]: I agree, I simplified the functions and error handling.

File: internal/controller/model_nodeport.go [hunk 6]
```diff
@@ -40,27 +48,51 @@ func NewNodePortLoadBalancerModelGenerator(
...
+func isValidIp(ipString string) (err error) {
+	ipParsed := net.ParseIP(ipString)
+	if ipParsed != nil {
+		return nil
+	}
+	return ErrInvalidIpAddress
+}
+
+func isIPv4Address(ipString string) (isIPv4 bool) {
+	return strings.Count(ipString, ":") == 0 && strings.Count(ipString, ".") == 3
```
Comment (horazont) [inline internal/controller/model_nodeport.go:60]: Fun fact: The following are valid IP addresses, at least on most UNIX systems:

- `0` (equivalent to `0.0.0.0`)
- `127.1` (equivalent to `127.0.0.1`)
- `10.133989` (equivalent to `10.2.11.101`)

But I don’t think we should/need to support those use cases :)

File: internal/controller/model_nodeport.go [hunk 7]
```diff
@@ -40,27 +48,51 @@ func NewNodePortLoadBalancerModelGenerator(
...
 }
 
-func (g *NodePortLoadBalancerModelGenerator) getDestinationAddresses() (result []string, err error) {
+func isValidIp(ipString string) (err error) {
+	ipParsed := net.ParseIP(ipString)
+	if ipParsed != nil {
+		return nil
+	}
+	return ErrInvalidIpAddress
+}
```
Comment (horazont) [inline internal/controller/model_nodeport.go:57]: `isXYZ` is expected to return a boolean. Checking for `!= nil` and then assuming that the test is, in fact, false is weird.

I suggest to rename it to `validateIpAddress`.

File: internal/controller/model_nodeport.go [hunk 8]
```diff
@@ -40,27 +48,51 @@ func NewNodePortLoadBalancerModelGenerator(
...
+
+func isIPv4Address(ipString string) (isIPv4 bool) {
```
Comment (horazont) [inline internal/controller/model_nodeport.go:59]: If you just use return, you don’t have to name the return value and can use `func is…(…) bool {` instead.

File: internal/controller/model_nodeport.go [hunk 9]
```diff
@@ -40,27 +48,51 @@ func NewNodePortLoadBalancerModelGenerator(
...
+	return strings.Count(ipString, ":") == 0 && strings.Count(ipString, ".") == 3
+}
+
+func isIPv6Address(ipString string) (isIPv6 bool) {
```
Comment (horazont) [inline internal/controller/model_nodeport.go:63]: See above re return value naming.

File: internal/controller/model_nodeport.go [hunk 10]
```diff
@@ -40,27 +48,51 @@ func NewNodePortLoadBalancerModelGenerator(
...
+	return strings.Count(ipString, ":") >= 2
+}
+
+func (g *NodePortLoadBalancerModelGenerator) getDestinationAddresses() (addresses_v4 []string, addresses_v6 []string, err error) {
```
Comment (horazont) [inline internal/controller/model_nodeport.go:67]: Please don’t use `snake_case` in golang… it is more of a `camelCase` language (re `addresses_v4` etc.)

**Review by horazont — CHANGES_REQUESTED** [review]

**Review by horazont — APPROVED** [review]
